In [1]:
# importar pandas
import pandas as pd

In [3]:
# crear una serie de numeros y hayar su media
numeros = pd.Series([1,2,3,45,62,6])
numeros.mean()

19.833333333333332

In [4]:
# Hallar la suma de estos numeros
numeros.sum()

119

In [6]:
# Crear una serie de tres colores diferentes y visualizarla
colores = pd.Series(['rojo', 'amarillo','verde'])
colores

0        rojo
1    amarillo
2       verde
dtype: object

In [8]:
# Crear una serie de tipos de autos
lista_autos = pd.Series(['sedan','SUV','Pick up'])
lista_autos

0      sedan
1        SUV
2    Pick up
dtype: object

In [10]:
# Combinar las series en un dataframe
tabla_autos = pd.DataFrame({'Tipo de auto':lista_autos, 'Color':colores})
tabla_autos

  Tipo de auto     Color
0        sedan      rojo
1          SUV  amarillo
2      Pick up     verde

In [12]:
ventas_autos = pd.read_csv('ventas-autos.csv')
ventas_autos

  Fabricante   Color  Kilometraje  Puertas Precio (USD)
0     Toyota  Blanco       150043        4    $4,000.00
1      Honda    Rojo        87899        4    $5,000.00
2     Toyota    Azul        32549        3    $7,000.00
3        BMW   Negro        11179        5   $22,000.00
4     Nissan  Blanco       213095        4    $3,500.00
5     Toyota    Rojo        99213        4    $4,500.00
6      Honda  Blanco        45698        4    $7,500.00
7      Honda  Blanco        54738        4    $7,000.00
8     Toyota  Blanco        60000        4    $6,250.00
9     Nissan    Rojo        31600        4    $9,700.00

In [14]:
# Analizar tipos de datos
ventas_autos.dtypes

Fabricante      object
Color           object
Kilometraje      int64
Puertas          int64
Precio (USD)    object
dtype: object

In [15]:
# Aplicar estadistica descriptiva
ventas_autos.describe()

         Kilometraje    Puertas
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [16]:
# Obtener informacion
ventas_autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fabricante    10 non-null     object
 1   Color         10 non-null     object
 2   Kilometraje   10 non-null     int64
 3   Puertas       10 non-null     int64
 4   Precio (USD)  10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [22]:
# Lista nombres de las columnas
ventas_autos.columns

Index(['Fabricante', 'Color', 'Kilometraje', 'Puertas', 'Precio (USD)'], dtype='object')

In [23]:
# Mostrar primeras X filas
ventas_autos.head(3)

  Fabricante   Color  Kilometraje  Puertas Precio (USD)
0     Toyota  Blanco       150043        4    $4,000.00
1      Honda    Rojo        87899        4    $5,000.00
2     Toyota    Azul        32549        3    $7,000.00

In [25]:
# Mostrar las ultimas X filas
ventas_autos.tail(3)

  Fabricante   Color  Kilometraje  Puertas Precio (USD)
7      Honda  Blanco        54738        4    $7,000.00
8     Toyota  Blanco        60000        4    $6,250.00
9     Nissan    Rojo        31600        4    $9,700.00

In [27]:
# Utilizar .loc para seleccinar una fila
ventas_autos.loc[3]

Fabricante             BMW
Color                Negro
Kilometraje          11179
Puertas                  5
Precio (USD)    $22,000.00
Name: 3, dtype: object

In [29]:
# Utilizar iloc para traer varias filas
ventas_autos.iloc[[3,7,9]]

  Fabricante   Color  Kilometraje  Puertas Precio (USD)
3        BMW   Negro        11179        5   $22,000.00
7      Honda  Blanco        54738        4    $7,000.00
9     Nissan    Rojo        31600        4    $9,700.00

In [30]:
# Seleccionar la columna kilometraje
ventas_autos['Kilometraje']

0    150043
1     87899
2     32549
3     11179
4    213095
5     99213
6     45698
7     54738
8     60000
9     31600
Name: Kilometraje, dtype: int64

In [31]:
# Valor media de kilometraje
ventas_autos['Kilometraje'].mean()

78601.4

In [32]:
# Seleccionar columnas con una condicion
ventas_autos[ventas_autos['Kilometraje'] > 100000]

  Fabricante   Color  Kilometraje  Puertas Precio (USD)
0     Toyota  Blanco       150043        4    $4,000.00
4     Nissan  Blanco       213095        4    $3,500.00

In [34]:
# Crear tabla cruzada
pd.crosstab(ventas_autos['Fabricante'], ventas_autos['Puertas'])

Puertas     3  4  5
Fabricante
BMW         0  0  1
Honda       0  3  0
Nissan      0  2  0
Toyota      1  3  0

In [39]:
# Agrupar columnas por fabricante y buscando el valor medio de los columnas numericas
ventas_autos.groupby(["Fabricante"]).mean(numeric_only=True)

              Kilometraje  Puertas
Fabricante
BMW          11179.000000     5.00
Honda        62778.333333     4.00
Nissan      122347.500000     4.00
Toyota       85451.250000     3.75